apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forge.fullname" . }}-scripts
  labels:
    {{- include "forge.labels" . | nindent 4 }}
data:
  init_forge.sh: |-
{{ (tpl (.Files.Get "files/init_forge.sh") .) | indent 4 }}
  cleanup_forge.sh: |-
{{ (tpl (.Files.Get "files/cleanup_forge.sh") .) | indent 4 }}
---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "forge.fullname" . }}-debug
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    app.kubernetes.io/name: forge-debug
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "forge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: forge-debug
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      restartPolicy: Never
      priorityClassName: {{ include "forge.fullname" . }}-high
      containers:
      - name: forge
        image: {{ .Values.forge.image.repo }}:{{ required "forge.image.tag must be set" .Values.forge.image.tag }}
        imagePullPolicy: {{ .Values.forge.image.pullPolicy }}
        command:
        - sh
        - -c
        - |-
          . /etc/forge/scripts/init_forge.sh
          tail -f /dev/null
          ret=$?
          . /etc/forge/scripts/cleanup_forge.sh
          exit $ret
        resources:
          {{- toYaml .Values.forge.resources | nindent 10 }}
        env:
        - name: RUST_BACKTRACE
          value: "1"
        volumeMounts:
        - name: forge-scripts
          mountPath: /etc/forge/scripts
        - name: vault-config
          mountPath: /etc/vault
        - name: vault-token
          mountPath: /opt/vault
      initContainers:
      {{- with .Values.vault }}
      - name: vault
        image: {{ .image.repo }}:{{ .image.tag }}
        imagePullPolicy: {{ .image.pullPolicy }}
        command: ["vault", "agent", "-config=/etc/vault/forge.json", "-exit-after-auth"]
        resources:
          {{- toYaml .resources | nindent 10 }}
        volumeMounts:
        - name: vault-config
          mountPath: /etc/vault
        - name: vault-token
          mountPath: /opt/vault
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      {{- end }}
      {{- with .Values.forge }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      volumes:
      - name: forge-scripts
        configMap:
          name: {{ include "forge.fullname" . }}-scripts
      - name: vault-config
        configMap:
          name: {{ include "forge.fullname" . }}-vault
      - name: vault-token
        emptyDir:
          medium: Memory
      serviceAccountName: {{ include "forge.serviceAccountName" . }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{.Values.imagePullSecret}}
      {{- end }}
