apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forge.fullname" . }}-vault
  labels:
    {{- include "forge.labels" . | nindent 4 }}
data:
  forge.json: |-
{{ tpl (.Files.Get "files/vault.json") . | indent 4 }}
{{- if .Values.vault.tls }}
{{ .Values.vault.tls | toYaml | indent 2 }}
{{ end }}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "forge.fullname" . }}-tokenreview
  labels:
    {{- include "forge.labels" . | nindent 4 }}
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "forge.fullname" . }}-tokenreview
  labels:
    {{- include "forge.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "forge.fullname" . }}-tokenreview
subjects:
- kind: ServiceAccount
  name: {{ include "forge.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
