[package]
name = "network-discovery"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos Network Peer Discovery"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
futures = "0.3.12"
once_cell = "1.10.0"
serde_yaml = "0.8.24"
tokio = { version = "1.8.1", features = ["full"] }

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics = { path = "../../crates/aptos-metrics" }
aptos-secure-storage = { path = "../../secure/storage" }
aptos-time-service = { path = "../../crates/aptos-time-service" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
channel = { path = "../../crates/channel" }
event-notifications = { path = "../../state-sync/inter-component/event-notifications" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }
network = { path = "../../network" }
short-hex-str = { path = "../../crates/short-hex-str" }

[dev-dependencies]
rand = "0.8.3"

aptos-config = { path = "../../config", features = ["testing"] }
aptos-temppath = { path = "../../crates/aptos-temppath" }
netcore = { path = "../netcore", features = ["fuzzing"] }
