[package]
name = "aptos-management"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos Management is a tool used to manage the configuration of a Node"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
hex = "0.4.3"
serde = { version = "1.0.137", features = ["rc"], default-features = false }
serde_yaml = "0.8.24"
structopt = "0.3.21"
thiserror = "1.0.31"

aptos-config = { path = ".." }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-global-constants = { path = "../global-constants" }
aptos-secure-storage = { path = "../../secure/storage" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-time-service = { path = "../../crates/aptos-time-service" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }

[dev-dependencies]
aptos-config = { path = "..", features = ["fuzzing"] }

[features]
testing = []
fuzzing = ["aptos-config/fuzzing"]
