# This compose file defines a Public Fullnode docker compose wrapper around aptos-node.
#
# In order to use, place a copy of the proper genesis.blob and waypoint.txt in this directory.
#
# Developer testnet genesis blob and waypoint can be found at:
# `curl https://devnet.aptoslabs.com/waypoint.txt --output waypoint.txt`
# `curl https://devnet.aptoslabs.com/genesis.blob --output genesis.blob`
#
# Note this compose comes with a pre-configured node.config for fullnodes, see
# public_full_node.yaml. The config is pretty well documented and aligns with instructions herein.
# It is intended for use with testnet but can be easily modified for other systems.
#
# To start the docker compose:
# `docker-compose -f docker-compose.yaml up -d`
#
# Additional information:
# * If you use this compose for different Aptos Networks, you will need remove the db volume first.
# * Aptos's testnet produces approximately 3 GB worth of chain data per day, so be patient while
# starting for the first time. As a sanity check, enter the container and check the increasing size
# of the db:
#   * `docker exec -it $CONTAINER_ID /bin/bash`
#   * `du -csm /opt/aptos/data``
#
# Monitoring:
# If you want to install the monitoring components for your fullnode
# you can symlink the ../monitoring folder into this directory.
# Note that you will need to rename the monitoring docker-compose.yaml file to avoid duplication.
# e.g. rename it to docker-compose.mon.yaml and run:
# `docker-compose -f docker-compose.yaml -f docker-compose.mon.yaml up -d`
# Dashboard can be accessed locally by loading localhost:3000 on your browser
version: "3.8"
services:
  fullnode:
    image: aptoslab/validator:devnet
    volumes:
      - type: volume
        source: db
        target: /opt/aptos/data
      - type: bind
        source: ./genesis.blob
        target: /opt/aptos/etc/genesis.blob
        read_only: true
      - type: bind
        source: ./public_full_node.yaml
        target: /opt/aptos/etc/node.yaml
        read_only: true
      - type: bind
        source: ./waypoint.txt
        target: /opt/aptos/etc/waypoint.txt
        read_only: true
    command: ["/opt/aptos/bin/aptos-node", "-f", "/opt/aptos/etc/node.yaml"]
    ports:
      - "8080:8080"
      - "9101:9101"
volumes:
  db:
