[package]
name = "vm-validator"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos vm validator"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
fail = "0.5.0"

aptos-state-view = { path = "../storage/state-view" }
aptos-types = { path = "../types" }
aptos-vm = { path = "../aptos-move/aptos-vm" }
aptos-workspace-hack = { path = "../crates/aptos-workspace-hack" }
executor = { path = "../execution/executor" }
storage-interface = { path = "../storage/storage-interface" }

[dev-dependencies]
rand = "0.8.3"

aptos-crypto = { path = "../crates/aptos-crypto", features = ["fuzzing"] }
aptos-temppath = { path = "../crates/aptos-temppath" }
aptos-transaction-builder = { path = "../sdk/transaction-builder" }
aptos-types = { path = "../types", features = ["fuzzing"] }
aptos-vm = { path = "../aptos-move/aptos-vm" }
aptosdb = { path = "../storage/aptosdb", features = ["fuzzing"] }
executor-test-helpers = { path = "../execution/executor-test-helpers" }
move-deps = { path = "../aptos-move/move-deps", features = ["address32"] }
vm-genesis = { path = "../aptos-move/vm-genesis" }

[features]
default = []
failpoints = ["fail/failpoints"]
fuzzing = ["aptos-types/fuzzing", "aptos-crypto/fuzzing", "aptosdb/fuzzing"]
