[package]
name = "aptos-operational-tool"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Tool for operators to manage nodes"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
bcs = "0.1.3"
futures = "0.3.12"
hex = "0.4.3"
itertools = "0.10.3"
rand = "0.8.3"
serde = { version = "1.0.137", features = ["rc"], default-features = false }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
structopt = "0.3.21"
thiserror = "1.0.31"
tokio = { version = "1.8.1", features = ["full"] }
tokio-util = { version = "0.6.4", features = ["compat"] }
toml = { version = "0.5.9", default-features = false }
url = "2.2.2"

aptos-config = { path = "../.." }
aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-global-constants = { path = "../../global-constants" }
aptos-infallible = { path = "../../../crates/aptos-infallible" }
aptos-management = { path = ".." }
aptos-rest-client = { path = "../../../crates/aptos-rest-client" }
aptos-secure-storage = { path = "../../../secure/storage" }
aptos-temppath = { path = "../../../crates/aptos-temppath" }
aptos-transaction-builder = { path = "../../../sdk/transaction-builder" }
aptos-types = { path = "../../../types" }
aptos-workspace-hack = { path = "../../../crates/aptos-workspace-hack" }
fallible = { path = "../../../crates/fallible" }
move-deps = { path = "../../../aptos-move/move-deps", features = ["address32"] }
netcore = { path = "../../../network/netcore" }
network = { path = "../../../network" }

[features]
testing = []
fuzzing = ["aptos-config/fuzzing"]
