validator:
  storage:
    class: ssd
  nodeSelector:
    cloud.google.com/gke-nodepool: validators

safetyrules:
  nodeSelector:
    cloud.google.com/gke-nodepool: validators

fullnode:
  nodeSelector:
    cloud.google.com/gke-nodepool: validators

monitoring:
  prometheus:
    storage:
      class: standard
  nodeSelector:
    cloud.google.com/gke-nodepool: utilities

logging:
  nodeSelector:
    cloud.google.com/gke-nodepool: utilities
