[workspace]
resolver = "2"

members = [
    "api",
    "api/types",
    "aptos-move/af-cli",
    "aptos-move/aptos-keygen",
    "aptos-move/aptos-resource-viewer",
    "aptos-move/aptos-transaction-benchmarks",
    "aptos-move/aptos-validator-interface",
    "aptos-move/aptos-vm",
    "aptos-move/e2e-tests",
    "aptos-move/e2e-testsuite",
    "aptos-move/framework",
    "aptos-move/framework/cached-packages",
    "aptos-move/genesis-viewer",
    "aptos-move/move-deps",
    "aptos-move/move-examples",
    "aptos-move/mvhashmap",
    "aptos-move/parallel-executor",
    "aptos-move/transaction-builder-generator",
    "aptos-move/transaction-replay",
    "aptos-move/vm-genesis",
    "aptos-move/writeset-transaction-generator",
    "aptos-node",
    "config",
    "config/global-constants",
    "config/management",
    "config/management/genesis",
    "config/management/operational",
    "config/seed-peer-generator",
    "consensus",
    "consensus/consensus-types",
    "consensus/safety-rules",
    "crates/aptos",
    "crates/aptos-bitvec",
    "crates/aptos-crypto",
    "crates/aptos-crypto-derive",
    "crates/aptos-faucet",
    "crates/aptos-id-generator",
    "crates/aptos-infallible",
    "crates/aptos-log-derive",
    "crates/aptos-logger",
    "crates/aptos-metrics",
    "crates/aptos-metrics-core",
    "crates/aptos-proptest-helpers",
    "crates/aptos-rate-limiter",
    "crates/aptos-rest-client",
    "crates/aptos-retrier",
    "crates/aptos-telemetry",
    "crates/aptos-temppath",
    "crates/aptos-time-service",
    "crates/aptos-workspace-hack",
    "crates/bounded-executor",
    "crates/channel",
    "crates/crash-handler",
    "crates/debug-interface",
    "crates/fallible",
    "crates/num-variants",
    "crates/proxy",
    "crates/short-hex-str",
    "crates/transaction-emitter",
    "devtools/x",
    "devtools/x-core",
    "devtools/x-lint",
    "ecosystem/indexer",
    "execution/db-bootstrapper",
    "execution/executor",
    "execution/executor-benchmark",
    "execution/executor-test-helpers",
    "execution/executor-types",
    "mempool",
    "network",
    "network/builder",
    "network/discovery",
    "network/memsocket",
    "network/netcore",
    "sdk",
    "sdk/transaction-builder",
    "secure/net",
    "secure/push-metrics",
    "secure/storage",
    "secure/storage/github",
    "secure/storage/vault",
    "state-sync/aptos-data-client",
    "state-sync/inter-component/consensus-notifications",
    "state-sync/inter-component/event-notifications",
    "state-sync/inter-component/mempool-notifications",
    "state-sync/state-sync-v1",
    "state-sync/state-sync-v2/data-streaming-service",
    "state-sync/state-sync-v2/state-sync-driver",
    "state-sync/state-sync-v2/state-sync-multiplexer",
    "state-sync/storage-service/client",
    "state-sync/storage-service/server",
    "state-sync/storage-service/types",
    "storage/accumulator",
    "storage/aptosdb",
    "storage/backup/backup-cli",
    "storage/backup/backup-service",
    "storage/jellyfish-merkle",
    "storage/schemadb",
    "storage/scratchpad",
    "storage/state-view",
    "storage/storage-client",
    "storage/storage-interface",
    "storage/storage-service",
    "testsuite/aptos-fuzzer",
    "testsuite/aptos-fuzzer/fuzz",
    "testsuite/forge",
    "testsuite/forge-cli",
    "testsuite/generate-format",
    "testsuite/smoke-test",
    "testsuite/testcases",
    "types",
    "vm-validator",
]

# NOTE: default-members is the complete list of binaries that form the "production Aptos codebase". These members should
# never include crates that require fuzzing features or test features. These are the crates we want built with no extra
# test-only code included.
#
# For more, see the "Conditional compilation for tests" section in documentation/coding_guidelines.md.
default-members = [
    "aptos-move/af-cli",
    "aptos-move/genesis-viewer",
    "aptos-move/transaction-replay",
    "aptos-node",
    "config/management/genesis",
    "config/management/operational",
    "config/seed-peer-generator",
    "consensus/safety-rules",
    "crates/aptos",
    "crates/aptos-faucet",
    "crates/aptos-rate-limiter",
    "aptos-move/framework",
    "aptos-move/transaction-builder-generator",
    "execution/db-bootstrapper",
    "storage/backup/backup-cli",
    "ecosystem/indexer",
]

[profile.release]
debug = true

[profile.bench]
debug = true

# Build guppy in opt mode so that x commands are faster.
[profile.dev.package.guppy]
opt-level = 3
