[package]
name = "aptos"
version = "0.1.1"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos tool for management of nodes and interacting with the blockchain"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
base64 = "0.13.0"
bcs = "0.1.3"
clap = "3.1.8"
hex = "0.4.3"
itertools = "0.10.3"
rand = "0.8.3"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = "1.0.137"
serde_json = "1.0.81"
serde_yaml = "0.8.24"
shadow-rs = "0.11.0"
tempfile = "3.3.0"
thiserror = "1.0.31"
tokio = { version = "1.8.1", features = ["full"] }
tokio-util = { version = "0.6.4", features = ["compat"] }
toml = "0.5.9"
uuid = { version = "1.0.0", features = ["v4", "serde"] }

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../aptos-crypto", features = [] }
aptos-github-client = { path = "../../secure/storage/github" }
aptos-logger = { path = "../aptos-logger" }
aptos-management = { path = "../../config/management" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
aptos-secure-storage = { path = "../../secure/storage" }
aptos-telemetry = { path = "../aptos-telemetry" }
aptos-temppath = { path = "../aptos-temppath" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
aptos-workspace-hack = { path = "../aptos-workspace-hack" }
aptosdb = { path = "../../storage/aptosdb" }
cached-framework-packages =  { path = "../../aptos-move/framework/cached-packages" }
executor = { path = "../../execution/executor" }
framework = { path = '../../aptos-move/framework' }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "testing"] }
short-hex-str = { path = "../short-hex-str" }
storage-interface = { path = "../../storage/storage-interface" }
vm-genesis = { path = "../../aptos-move/vm-genesis" }

[build-dependencies]
shadow-rs = "0.11.0"
