[package]
name = "seed-peer-generator"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos seed peer generator"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
hex = "0.4.3"
rand = "0.8.3"
serde_yaml = "0.8.24"
structopt = "0.3.21"
thiserror = "1.0.31"
tokio = { version = "1.8.1", features = ["full"] }
url = "2.2.2"

aptos-config = { path = ".." }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }

[dev-dependencies]
aptos-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
