[package]
name = "storage-service-server"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "The Aptos storage service (server-side)"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.3"
bytes = "1.1.0"
futures = "0.3.12"
lru = "0.7.5"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.8.1", features = ["rt", "macros"], default-features = false }

aptos-config = { path = "../../../config" }
aptos-infallible = { path = "../../../crates/aptos-infallible" }
aptos-logger = { path = "../../../crates/aptos-logger" }
aptos-metrics = { path = "../../../crates/aptos-metrics" }
aptos-time-service = { path = "../../../crates/aptos-time-service", features = ["async"] }
aptos-types = { path = "../../../types" }
aptos-workspace-hack = { path = "../../../crates/aptos-workspace-hack" }
bounded-executor = { path = "../../../crates/bounded-executor" }
channel = { path = "../../../crates/channel" }
network = { path = "../../../network" }
storage-interface = { path = "../../../storage/storage-interface" }
storage-service-types = { path = "../types" }

[dev-dependencies]
anyhow = "1.0.57"
claim = "0.5.0"
mockall = "0.11.0"

aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-time-service = { path = "../../../crates/aptos-time-service", features = ["async", "testing"] }
aptos-types = { path = "../../../types" }
move-deps = { path = "../../../aptos-move/move-deps", features = ["address32"] }
storage-interface = { path = "../../../storage/storage-interface" }
