[package]
name = "aptos-api-types"
version = "0.0.1"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos API Types"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
hex = "0.4.3"
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"
warp = { version = "0.3.2", features = ["default"] }

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }

[dev-dependencies]
move-deps = { path = "../../aptos-move/move-deps" }
