[package]
name = "aptos-temppath"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Temporary path utilities"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
hex = "0.4.3"
rand = "0.8.3"

aptos-workspace-hack = { path = "../aptos-workspace-hack" }
