[package]
name = "channel"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "An implementation of a channel with configurable QoS"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
futures = "0.3.12"

aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-metrics = { path = "../../crates/aptos-metrics" }
aptos-workspace-hack = { path = "../aptos-workspace-hack" }

[dev-dependencies]
tokio = { version = "1.8.1", features = ["full"] }

aptos-types = { path = "../../types" }
