[package]
name = "aptos-node"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos node"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.3"
fail = "0.5.0"
futures = "0.3.12"
hex = "0.4.3"
jemallocator = { version = "0.3.2", features = ["profiling", "unprefixed_malloc_on_supported_platforms"] }
rand = "0.8.3"
structopt = "0.3.21"
tokio = { version = "1.8.1", features = ["full"] }
tokio-stream = "0.1.4"

aptos-api = { path = "../api" }
aptos-config = { path = "../config" }
aptos-crypto = { path = "../crates/aptos-crypto" }
aptos-data-client = { path = "../state-sync/aptos-data-client" }
aptos-genesis-tool = { path = "../config/management/genesis", features = ["testing"] }
aptos-infallible = { path = "../crates/aptos-infallible" }
aptos-logger = { path = "../crates/aptos-logger" }
aptos-mempool = { path = "../mempool" }
aptos-metrics = { path = "../crates/aptos-metrics" }
aptos-secure-storage = { path = "../secure/storage" }
aptos-state-view = { path = "../storage/state-view" }
aptos-telemetry = { path = "../crates/aptos-telemetry" }
aptos-temppath = { path = "../crates/aptos-temppath" }
aptos-time-service = { path = "../crates/aptos-time-service" }
aptos-types = { path = "../types" }
aptos-vm = { path = "../aptos-move/aptos-vm" }
aptos-workspace-hack = { path = "../crates/aptos-workspace-hack" }
aptosdb = { path = "../storage/aptosdb" }
backup-service = { path = "../storage/backup/backup-service" }
cached-framework-packages = { path = "../aptos-move/framework/cached-packages" }
consensus = { path = "../consensus" }
consensus-notifications = { path = "../state-sync/inter-component/consensus-notifications" }
crash-handler = { path = "../crates/crash-handler" }
data-streaming-service = { path = "../state-sync/state-sync-v2/data-streaming-service" }
debug-interface = { path = "../crates/debug-interface" }
event-notifications = { path = "../state-sync/inter-component/event-notifications" }
executor = { path = "../execution/executor" }
executor-types = { path = "../execution/executor-types" }
framework = { path = "../aptos-move/framework" }
mempool-notifications = { path = "../state-sync/inter-component/mempool-notifications" }
network = { path = "../network" }
network-builder = { path = "../network/builder" }
state-sync-multiplexer = { path = "../state-sync/state-sync-v2/state-sync-multiplexer" }
state-sync-v1 = { path = "../state-sync/state-sync-v1" }
storage-client = { path = "../storage/storage-client" }
storage-interface = { path = "../storage/storage-interface" }
storage-service = { path = "../storage/storage-service" }
storage-service-client = { path = "../state-sync/storage-service/client" }
storage-service-server = { path = "../state-sync/storage-service/server" }

[features]
default = []
assert-private-keys-not-cloneable = ["aptos-crypto/assert-private-keys-not-cloneable"]
failpoints = ["fail/failpoints", "consensus/failpoints", "executor/failpoints", "aptos-mempool/failpoints", "aptos-api/failpoints"]
