[package]
name = "storage-service"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos storage service"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
rand = { version = "0.8.3", optional = true }

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics = { path = "../../crates/aptos-metrics" }
aptos-secure-net = { path = "../../secure/net" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
aptosdb = { path = "../aptosdb" }
storage-client = { path = "../storage-client", optional = true }
storage-interface = { path = "../storage-interface" }

[dev-dependencies]
itertools = "0.10.0"
proptest = "1.0.0"

aptos-temppath = { path = "../../crates/aptos-temppath" }
aptosdb = { path = "../aptosdb", features = ["fuzzing"] }
storage-client = { path = "../storage-client" }

[features]
default = []
fuzzing = ["aptosdb/fuzzing", "rand"]
