[package]
name = "genesis-viewer"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos genesis viewer"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
structopt = "0.3.21"

aptos-resource-viewer = { path = "../aptos-resource-viewer" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
cached-framework-packages =  { path = "../framework/cached-packages" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "table-extension"] }
vm-genesis = { path = "../vm-genesis" }
