[package]
name = "language-e2e-testsuite"
version = "0.1.0"
edition = "2018"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Move language e2e tests"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
proptest = "1.0.0"

aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }
aptos-keygen = { path = "../aptos-keygen" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-parallel-executor = { path = "../parallel-executor" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptos-vm = { path = "../aptos-vm" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
aptos-writeset-generator = { path = "../writeset-transaction-generator" }
cached-framework-packages =  { path = "../framework/cached-packages" }
language-e2e-tests = { path = "../e2e-tests" }
move-deps = { path = "../move-deps", features = ["address32"] }

[features]
default = ["aptos-transaction-builder/fuzzing"]
