[package]
name = "transaction-emitter"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos transaction emitter for testing"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
futures = "0.3.12"
itertools = "0.10.3"
rand = "0.8.3"
rand_core = "0.6.2"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
structopt = "0.3.21"
termion = "1.5.6"
tokio = { version = "1.8.1", features = ["full"] }

aptos = { path = "../aptos" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../aptos-crypto" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-workspace-hack = { path = "../aptos-workspace-hack" }
