[package]
name = "aptos-workspace-hack"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos workspace hack"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

### BEGIN HAKARI SECTION
[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace", "std"] }
backtrace = { version = "0.3.58", features = ["addr2line", "gimli-symbolize", "miniz_oxide", "object", "serde", "std"] }
byteorder = { version = "1.4.3", features = ["std"] }
bytes = { version = "1.1.0", features = ["serde", "std"] }
chrono = { version = "0.4.19", features = ["clock", "libc", "oldtime", "serde", "std", "time", "winapi"] }
clap = { version = "2.34.0", features = ["ansi_term", "atty", "color", "strsim", "suggestions", "vec_map"] }
crossbeam-channel = { version = "0.5.4", features = ["crossbeam-utils", "std"] }
crossbeam-deque = { version = "0.8.1", features = ["crossbeam-epoch", "crossbeam-utils", "std"] }
crossbeam-queue = { version = "0.3.5", features = ["alloc", "std"] }
crossbeam-utils = { version = "0.8.8", features = ["lazy_static", "std"] }
crypto-common = { version = "0.1.3", default-features = false, features = ["std"] }
diesel = { version = "1.4.8", features = ["32-column-tables", "bigdecimal", "bitflags", "chrono", "num-bigint", "num-integer", "num-traits", "numeric", "postgres", "pq-sys", "r2d2", "serde_json", "with-deprecated"] }
digest = { version = "0.10.3", features = ["alloc", "block-buffer", "core-api", "std"] }
either = { version = "1.6.1", features = ["use_std"] }
futures-channel = { version = "0.3.21", features = ["alloc", "futures-sink", "sink", "std"] }
futures-core = { version = "0.3.21", features = ["alloc", "std"] }
futures-io = { version = "0.3.21", features = ["std"] }
futures-sink = { version = "0.3.21", features = ["alloc", "std"] }
futures-util = { version = "0.3.17", features = ["alloc", "async-await", "async-await-macro", "channel", "futures-channel", "futures-io", "futures-macro", "futures-sink", "io", "memchr", "proc-macro-hack", "proc-macro-nested", "sink", "slab", "std"] }
generic-array = { version = "0.14.5", default-features = false, features = ["more_lengths"] }
getrandom = { version = "0.2.6", default-features = false, features = ["std"] }
hashbrown = { version = "0.11.2", features = ["ahash", "inline-more", "raw"] }
hyper = { version = "0.14.18", features = ["client", "full", "h2", "http1", "http2", "runtime", "server", "socket2", "stream", "tcp"] }
include_dir = { version = "0.7.2", features = ["glob"] }
itertools = { version = "0.10.3", features = ["use_alloc", "use_std"] }
libc = { version = "0.2.125", features = ["std"] }
log = { version = "0.4.17", default-features = false, features = ["std"] }
memchr = { version = "2.5.0", features = ["std", "use_std"] }
num-integer = { version = "0.1.45", features = ["std"] }
num-traits = { version = "0.2.15", features = ["std"] }
parking_lot = { version = "0.12.0", features = ["send_guard"] }
rand = { version = "0.8.4", features = ["alloc", "getrandom", "libc", "rand_chacha", "rand_hc", "small_rng", "std", "std_rng"] }
regex = { version = "1.5.5", features = ["aho-corasick", "memchr", "perf", "perf-cache", "perf-dfa", "perf-inline", "perf-literal", "std", "unicode", "unicode-age", "unicode-bool", "unicode-case", "unicode-gencat", "unicode-perl", "unicode-script", "unicode-segment"] }
regex-syntax = { version = "0.6.25", features = ["unicode", "unicode-age", "unicode-bool", "unicode-case", "unicode-gencat", "unicode-perl", "unicode-script", "unicode-segment"] }
reqwest = { version = "0.11.10", features = ["__tls", "blocking", "cookie_crate", "cookie_store", "cookies", "default-tls", "hyper-tls", "json", "native-tls-crate", "proc-macro-hack", "serde_json", "stream", "tokio-native-tls", "tokio-util"] }
rusty-fork = { version = "0.3.0", features = ["timeout", "wait-timeout"] }
serde = { version = "1.0.137", features = ["alloc", "derive", "rc", "serde_derive", "std"] }
serde_json = { version = "1.0.81", features = ["indexmap", "preserve_order", "std"] }
sha-1 = { version = "0.10.0", features = ["std"] }
standback = { version = "0.2.17", default-features = false, features = ["std"] }
tokio = { version = "1.18.1", features = ["bytes", "fs", "full", "io-std", "io-util", "libc", "macros", "memchr", "mio", "net", "num_cpus", "once_cell", "parking_lot", "process", "rt", "rt-multi-thread", "signal", "signal-hook-registry", "socket2", "sync", "test-util", "time", "tokio-macros"] }
tokio-util = { version = "0.6.9", features = ["codec", "compat", "futures-io", "io"] }
toml = { version = "0.5.9" }
tracing = { version = "0.1.34", features = ["attributes", "log", "std", "tracing-attributes"] }
tracing-core = { version = "0.1.26", features = ["lazy_static", "std"] }
warp = { version = "0.3.2", features = ["multipart", "tls", "tokio-rustls", "tokio-tungstenite", "websocket"] }

[build-dependencies]
anyhow = { version = "1.0.57", features = ["backtrace", "std"] }
backtrace = { version = "0.3.58", features = ["addr2line", "gimli-symbolize", "miniz_oxide", "object", "serde", "std"] }
byteorder = { version = "1.4.3", features = ["std"] }
bytes = { version = "1.1.0", features = ["serde", "std"] }
cc = { version = "1.0.73", default-features = false, features = ["jobserver", "parallel"] }
chrono = { version = "0.4.19", features = ["clock", "libc", "oldtime", "serde", "std", "time", "winapi"] }
clap = { version = "2.34.0", features = ["ansi_term", "atty", "color", "strsim", "suggestions", "vec_map"] }
crossbeam-channel = { version = "0.5.4", features = ["crossbeam-utils", "std"] }
crossbeam-deque = { version = "0.8.1", features = ["crossbeam-epoch", "crossbeam-utils", "std"] }
crossbeam-queue = { version = "0.3.5", features = ["alloc", "std"] }
crossbeam-utils = { version = "0.8.8", features = ["lazy_static", "std"] }
crypto-common = { version = "0.1.3", default-features = false, features = ["std"] }
diesel = { version = "1.4.8", features = ["32-column-tables", "bigdecimal", "bitflags", "chrono", "num-bigint", "num-integer", "num-traits", "numeric", "postgres", "pq-sys", "r2d2", "serde_json", "with-deprecated"] }
digest = { version = "0.10.3", features = ["alloc", "block-buffer", "core-api", "std"] }
either = { version = "1.6.1", features = ["use_std"] }
futures-channel = { version = "0.3.21", features = ["alloc", "futures-sink", "sink", "std"] }
futures-core = { version = "0.3.21", features = ["alloc", "std"] }
futures-io = { version = "0.3.21", features = ["std"] }
futures-sink = { version = "0.3.21", features = ["alloc", "std"] }
futures-util = { version = "0.3.17", features = ["alloc", "async-await", "async-await-macro", "channel", "futures-channel", "futures-io", "futures-macro", "futures-sink", "io", "memchr", "proc-macro-hack", "proc-macro-nested", "sink", "slab", "std"] }
generic-array = { version = "0.14.5", default-features = false, features = ["more_lengths"] }
getrandom = { version = "0.2.6", default-features = false, features = ["std"] }
hashbrown = { version = "0.11.2", features = ["ahash", "inline-more", "raw"] }
hyper = { version = "0.14.18", features = ["client", "full", "h2", "http1", "http2", "runtime", "server", "socket2", "stream", "tcp"] }
include_dir = { version = "0.7.2", features = ["glob"] }
itertools = { version = "0.10.3", features = ["use_alloc", "use_std"] }
libc = { version = "0.2.125", features = ["std"] }
log = { version = "0.4.17", default-features = false, features = ["std"] }
memchr = { version = "2.5.0", features = ["std", "use_std"] }
num-integer = { version = "0.1.45", features = ["std"] }
num-traits = { version = "0.2.15", features = ["std"] }
parking_lot = { version = "0.12.0", features = ["send_guard"] }
rand = { version = "0.8.4", features = ["alloc", "getrandom", "libc", "rand_chacha", "rand_hc", "small_rng", "std", "std_rng"] }
regex = { version = "1.5.5", features = ["aho-corasick", "memchr", "perf", "perf-cache", "perf-dfa", "perf-inline", "perf-literal", "std", "unicode", "unicode-age", "unicode-bool", "unicode-case", "unicode-gencat", "unicode-perl", "unicode-script", "unicode-segment"] }
regex-syntax = { version = "0.6.25", features = ["unicode", "unicode-age", "unicode-bool", "unicode-case", "unicode-gencat", "unicode-perl", "unicode-script", "unicode-segment"] }
reqwest = { version = "0.11.10", features = ["__tls", "blocking", "cookie_crate", "cookie_store", "cookies", "default-tls", "hyper-tls", "json", "native-tls-crate", "proc-macro-hack", "serde_json", "stream", "tokio-native-tls", "tokio-util"] }
rusty-fork = { version = "0.3.0", features = ["timeout", "wait-timeout"] }
serde = { version = "1.0.137", features = ["alloc", "derive", "rc", "serde_derive", "std"] }
serde_json = { version = "1.0.81", features = ["indexmap", "preserve_order", "std"] }
sha-1 = { version = "0.10.0", features = ["std"] }
standback = { version = "0.2.17", default-features = false, features = ["std"] }
syn = { version = "1.0.92", features = ["clone-impls", "derive", "extra-traits", "fold", "full", "parsing", "printing", "proc-macro", "quote", "visit", "visit-mut"] }
tokio = { version = "1.18.1", features = ["bytes", "fs", "full", "io-std", "io-util", "libc", "macros", "memchr", "mio", "net", "num_cpus", "once_cell", "parking_lot", "process", "rt", "rt-multi-thread", "signal", "signal-hook-registry", "socket2", "sync", "test-util", "time", "tokio-macros"] }
tokio-util = { version = "0.6.9", features = ["codec", "compat", "futures-io", "io"] }
toml = { version = "0.5.9" }
tracing = { version = "0.1.34", features = ["attributes", "log", "std", "tracing-attributes"] }
tracing-core = { version = "0.1.26", features = ["lazy_static", "std"] }
warp = { version = "0.3.2", features = ["multipart", "tls", "tokio-rustls", "tokio-tungstenite", "websocket"] }

### END HAKARI SECTION
