[package]
name = "aptos-metrics"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos metrics utilities"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.12"
hyper = { version = "0.14.18", features = ["full"] }
once_cell = "1.10.0"
prometheus = { version = "0.13.0", default-features = false }
serde_json = "1.0.81"
sysinfo = "0.23.11"
tokio = { version = "1.8.1", features = ["full"] }

aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../aptos-metrics-core" }
aptos-workspace-hack = { path = "../aptos-workspace-hack" }

[dev-dependencies]
assert_approx_eq = "1.1.0"
rusty-fork = "0.3.0"
