[package]
name = "executor-benchmark"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos executor benchmark"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
chrono = "0.4.19"
criterion = "0.3.5"
indicatif = "0.15.0"
jemallocator = { version = "0.3.2", features = ["profiling", "unprefixed_malloc_on_supported_platforms"] }
rand = "0.8.3"
rayon = "1.5.2"
serde = "1.0.137"
structopt = "0.3.21"
toml = "0.5.9"

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-genesis-tool = { path = "../../config/management/genesis", features = ["testing"] }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-jellyfish-merkle = { path = "../../storage/jellyfish-merkle" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-sdk = { path = "../../sdk" }
aptos-secure-push-metrics = { path = "../../secure/push-metrics" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
aptosdb = { path = "../../storage/aptosdb" }
executor = { path = "../executor" }
executor-types = { path = "../executor-types" }
schemadb = { path = "../../storage/schemadb" }
storage-client = { path = "../../storage/storage-client" }
storage-interface = { path = "../../storage/storage-interface" }

[dev-dependencies]
aptos-temppath = { path = "../../crates/aptos-temppath" }

[features]
default = []
fuzzing = ["aptos-config/fuzzing", "aptos-crypto/fuzzing", "aptos-types/fuzzing"]

[[bench]]
name = "executor_benchmark"
harness = false
