apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aptos-validator.fullname" . }}-fullnode
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}

{{- range .Values.fullnode.groups }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "aptos-validator.fullname" $ }}-{{ .name }}
  labels:
    {{- include "aptos-validator.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "aptos-validator.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/name: fullnode
    group: {{ .name }}
  ports:
  - name: aptosnet
    port: 6182
  - name: api
    port: 8080
  - name: backup
    port: 6186

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aptos-validator.fullname" $ }}-{{ .name }}-e{{ $.Values.chain.era }}
  labels:
    {{- include "aptos-validator.labels" $ | nindent 4 }}
    app.kubernetes.io/name: fullnode
    group: {{ .name }}
spec:
  serviceName: {{ include "aptos-validator.fullname" $ }}-{{ .name }}
  replicas: {{ .replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "aptos-validator.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/name: fullnode
      group: {{ .name }}
  volumeClaimTemplates:
  - metadata:
      name: fn
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ $.Values.fullnode.storage.class }}
      resources:
        requests:
          storage: {{ $.Values.fullnode.storage.size }}
  template:
    metadata:
      labels:
        {{- include "aptos-validator.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/name: fullnode
        group: {{ .name }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        checksum/fullnode.yaml: {{ tpl ($.Files.Get "files/configs/fullnode.yaml") $ | sha256sum }}
        checksum/vault.json: {{ tpl ($.Files.Get "files/vault.json") $ | sha256sum }}
    spec:
      priorityClassName: {{ include "aptos-validator.fullname" $ }}-medium
      terminationGracePeriodSeconds: 0
      containers:
      - name: fullnode
        image: {{ $.Values.validator.image.repo }}:{{ $.Values.validator.image.tag | default $.Values.imageTag }}
        imagePullPolicy: {{ $.Values.validator.image.pullPolicy }}
        command:
        - bash
        - -c
        - |-
          set -ex
          while [ ! -e /opt/vault/token ] && [ $SECONDS -lt 30 ]; do sleep 1; done
          exec /opt/aptos/bin/aptos-node -f /opt/aptos/etc/fullnode.yaml
      {{- with $.Values.fullnode }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        env:
        - name: RUST_LOG
          value: {{ .rust_log }}
        - name: RUST_LOG_REMOTE
          value: {{ .rust_log_remote }}
      {{- end }}
        - name: RUST_BACKTRACE
          value: "1"
        - name: STRUCT_LOG_TCP_ADDR
          value: '{{ include "aptos-validator.fullname" $ }}-logging:5044'
        volumeMounts:
        - name: aptos-config
          mountPath: /opt/aptos/etc
        - name: genesis-config
          mountPath: /opt/aptos/genesis
        - name: fn
          mountPath: /opt/aptos/data
        - name: vault-config
          mountPath: /etc/vault
        - name: vault-token
          mountPath: /opt/vault
        ports:
        - containerPort: 6181
        - containerPort: 6182
        - containerPort: 8080
        - containerPort: 9101
        livenessProbe:
          tcpSocket:
            port: 9101
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 6182
        securityContext:
          {{- if $.Values.enablePrivilegedMode }}
          privileged: true
          {{- else }}
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          {{- end }}
      {{- with $.Values.vault }}
      - name: vault
        image: {{ .image.repo }}:{{ .image.tag }}
        imagePullPolicy: {{ .image.pullPolicy }}
        command: ["vault", "agent", "-config=/etc/vault/fullnode.json"]
        resources:
          {{- toYaml .resources | nindent 10 }}
        volumeMounts:
        - name: vault-config
          mountPath: /etc/vault
        - name: vault-token
          mountPath: /opt/vault
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      {{- end }}
      {{- with $.Values.fullnode }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
        fsGroup: 6180
      {{- end }}
      volumes:
      - name: aptos-config
        configMap:
          name: {{ include "aptos-validator.fullname" $ }}
      - name: genesis-config
        configMap:
          name: {{ include "aptos-validator.fullname" $ }}-genesis-e{{ $.Values.chain.era }}
      - name: vault-config
        configMap:
          name: {{ include "aptos-validator.fullname" $ }}-vault
      - name: vault-token
        emptyDir:
          medium: Memory
      serviceAccountName: {{ include "aptos-validator.fullname" $ }}-fullnode
      {{- if $.Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.imagePullSecret }}
      {{- end }}

{{- end }}
