apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "aptos-validator.fullname" . }}-high
value: 50000

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "aptos-validator.fullname" . }}-medium
value: 30000
