{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aptos-validator.serviceAccountName" . }}
  labels:
{{ include "aptos-validator.labels" . | nindent 4 }}
{{- end }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aptos-validator.fullname" . }}-backup
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.backup.serviceAccount.annotations | nindent 4 }}
