apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aptos-validator.fullname" . }}-tools
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "aptos-validator.fullname" . }}-tools
  replicas: 0
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "aptos-validator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: tools
  template:
    metadata:
      labels:
        {{- include "aptos-validator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: tools
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
      - name: tools
        image: {{ .Values.tools.image.repo }}:{{ .Values.tools.image.tag | default .Values.imageTag }}
      {{- with .Values.tools }}
        imagePullPolicy: {{ .image.pullPolicy }}
      {{- end }}
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: aptos-data
          mountPath: /opt/aptos/data
        - name: tmp
          mountPath: /tmp
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
        fsGroup: 6180
      volumes:
      - name: aptos-data
        persistentVolumeClaim:
          claimName: {{ include "aptos-validator.fullname" . }}-validator-e{{ .Values.chain.era }}
      - name: tmp
        emptyDir: {}
      serviceAccountName: {{ include "aptos-validator.serviceAccountName" . }}
