[package]
name = "testcases"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos compatibility tests"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
rand = "0.8.3"
tokio = { version = "1.8.1", features = ["full"] }

aptos-logger = { path = "../../crates/aptos-logger" }
aptos-operational-tool = { path = "../../config/management/operational", features = ["testing"] }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
forge = { path = "../forge" }

[[test]]
name = "forge-local-compatibility"
harness = false

[[test]]
name = "forge-local-performance"
harness = false
