[package]
name = "scratchpad"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos scratchpad"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
arc-swap = "1.5.0"
bitvec = { version = "0.19.4" }
itertools = "0.10.0"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
rayon = "1.5.2"
thiserror = "1.0.24"

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-metrics = { path = "../../crates/aptos-metrics" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }

[dev-dependencies]
bitvec = "0.19.4"
criterion = "0.3.5"
once_cell = "1.10.0"
proptest = "1.0.0"
rand = "0.8.3"

aptos-types = { path = "../../types", features = ["fuzzing"] }
storage-interface = { path = "../storage-interface" }

[features]
fuzzing = ["aptos-types/fuzzing", "proptest"]
bench = ["proptest"]

[[bench]]
name = "sparse_merkle"
harness = false
required-features = ["bench"]

[lib]
# Allow Criterion benchmarks to take command line arguments
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false
