{{- if .Values.faucet_test.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "testnet.fullname" . }}-faucet-test
  labels:
    {{- include "testnet.labels" . | nindent 4 }}
data:
  commands.txt: |-
{{ .Files.Get "files/commands.txt" | indent 4 }}

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "testnet.fullname" . }}-faucet-test
  labels:
    {{- include "testnet.labels" . | nindent 4 }}
    app.kubernetes.io/name: faucet-test
spec:
  concurrencyPolicy: Replace
  schedule: {{ printf "%d * * * *" (int .Values.faucet_test.offsetMins) | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "testnet.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/name: faucet-test
          annotations:
            seccomp.security.alpha.kubernetes.io/pod: runtime/default
        spec:
          restartPolicy: Never
          priorityClassName: {{ include "testnet.fullname" . }}-high
          containers:
          - name: faucet-test
            image: {{ .Values.faucet.image.repo }}:{{ .Values.faucet.image.tag | default .Values.imageTag }}
            imagePullPolicy: {{ .Values.faucet.image.pullPolicy }}
            workingDir: /tmp
            command: ["/bin/sh", "-c"]
            args:
            - /opt/aptos/bin/cli
              --chain-id={{ .Values.genesis.chain_id | default .Values.genesis.era }}
              --url=http://{{ include "testnet.fullname" . }}-jsonrpc
              --faucet-url=http://{{ include "testnet.fullname" . }}-faucet
              --waypoint=$(cat /opt/aptos/etc/waypoint.txt)
              < /opt/aptos/cmd/commands.txt 2>&1 | tee /tmp/out.txt;
              grep -i error /tmp/out.txt && echo "Failure" && exit 1 || echo "Success" && exit 0
          {{- with .Values.faucet_test }}
            env:
            - name: RUST_BACKTRACE
              value: "1"
            volumeMounts:
            - name: faucet-test-commands
              mountPath: /opt/aptos/cmd
            - name: genesis
              mountPath: /opt/aptos/etc
            - name: tmp
              mountPath: /tmp
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
          {{- with .nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 6180
            runAsGroup: 6180
            fsGroup: 6180
          {{- end }}
          volumes:
          - name: faucet-test-commands
            configMap:
              name: {{ include "testnet.fullname" . }}-faucet-test
          - name: genesis
            configMap:
              name: {{ include "testnet.fullname" .}}-genesis-e{{ .Values.genesis.era }}
          - name: tmp
            emptyDir: {}
          serviceAccountName: {{ include "testnet.serviceAccountName" . }}
          {{- if .Values.imagePullSecret }}
          imagePullSecrets:
          - name: {{.Values.imagePullSecret}}
          {{- end }}
{{- end }}
