apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "testnet.fullname" . }}
  labels:
    {{- include "testnet.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: {{ .Values.service.aws_tags | quote }}
    {{- if .Values.ingress.loadBalancerSourceRanges }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ join "," .Values.ingress.loadBalancerSourceRanges }}
    {{- end }}
    {{- if .Values.service.domain }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.domain }}
    {{- end }}
    {{- if .Values.ingress.acm_certificate }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.acm_certificate }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    {{- end }}
    {{- if .Values.ingress.wafAclArn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.wafAclArn }}
    {{- end }}
    {{- if .Values.ingress.enableStickyness }}
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds={{ .Values.ingress.cookieDurationSeconds }}
    alb.ingress.kubernetes.io/target-type: ip
    {{- end }}
spec:
  rules:
  {{- if .Values.faucet.enabled }}
  - host: faucet.{{ .Values.service.domain }}
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: {{ include "testnet.fullname" . }}-faucet
            port:
              number: 80
  {{- end }}
  {{- if .Values.service.pfn.exposeApi }}
  - host: pfn.{{ .Values.service.domain }}
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: {{ include "testnet.fullname" . }}-pfn
            port:
              number: 80
  {{- end }}
  {{- if .Values.service.fullnode.exposeApi }}
  - host: fullnode.{{ .Values.service.domain }}
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: {{ include "testnet.fullname" . }}-api
            port:
              number: 80
  {{- end }}
  - http:
      paths:
      - path: /waypoint.txt
        pathType: Exact
        backend:
          service:
            name: {{ include "testnet.fullname" . }}-waypoint
            port:
              number: 80
      - path: /chainid.txt
        pathType: Exact
        backend:
          service:
            name: {{ include "testnet.fullname" . }}-waypoint
            port:
              number: 80
      - path: /era.txt
        pathType: Exact
        backend:
          service:
            name: {{ include "testnet.fullname" . }}-waypoint
            port:
              number: 80
      - path: /genesis.blob
        pathType: Exact
        backend:
          service:
            name: {{ include "testnet.fullname" . }}-waypoint
            port:
              number: 80
      {{- if .Values.service.fullnode.exposeApi }}
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: {{ include "testnet.fullname" . }}-api
            port:
              number: 80
      {{- end }}
