{{- if .Values.load_test.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "testnet.fullname" . }}-load-test
  labels:
    {{- include "testnet.labels" . | nindent 4 }}
    app.kubernetes.io/name: load-test
spec:
  concurrencyPolicy: Replace
  schedule: {{ printf "*/%d * * * *" (int .Values.load_test.intervalMins) | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "testnet.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/name: load-test
          annotations:
            seccomp.security.alpha.kubernetes.io/pod: runtime/default
        spec:
          restartPolicy: Never
          priorityClassName: {{ include "testnet.fullname" . }}-high
          containers:
          - name: load-test
            image: {{ .Values.load_test.image.repo }}:{{ .Values.load_test.image.tag | default .Values.imageTag }}
            imagePullPolicy: {{ .Values.load_test.image.pullPolicy }}
            command:
            - transaction-emitter
            - --emit-tx
            - --mint-file=/opt/aptos/etc/mint.key
            - --chain-id={{ .Values.genesis.chain_id | default .Values.genesis.era }}
            {{- if .Values.validatorLite }}
            - --peers={{- range $i, $e := until (int .Values.genesis.numValidators) -}}val{{$i}}-aptos-validator-validator-lb:80,{{- end -}}
            {{- else }}
            - --peers={{- range $i, $e := until (int .Values.genesis.numValidators) -}}val{{$i}}-aptos-validator-fullnode-lb:80,{{- end -}}
            {{- end }}
          {{- with .Values.load_test }}
            - --duration={{ .config.duration }}
            - --accounts-per-client={{ .config.accounts_per_client }}
            - --workers-per-ac={{ .config.workers_per_ac }}
            {{- if .config.enableBurst }}
            - --burst
            - --wait-millis={{ .config.waitMillis }}
            {{- end }}
            env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: REUSE_ACC
              value: "1"
            volumeMounts:
            - name: faucet-configs
              mountPath: /opt/aptos/etc
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
          {{- with .nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 6180
            runAsGroup: 6180
            fsGroup: 6180
          {{- end }}
          volumes:
          - name: faucet-configs
            secret:
              secretName: {{ include "testnet.fullname" . }}-faucet-e{{ .Values.genesis.era }}
          serviceAccountName: {{ include "testnet.serviceAccountName" . }}
          {{- if .Values.imagePullSecret }}
          imagePullSecrets:
          - name: {{.Values.imagePullSecret}}
          {{- end }}
{{- end }}
