{{- $fullName := include "testnet.fullname" . -}}
{{- $labels := include "testnet.labels" . -}}
{{- $domain := .Values.service.domain -}}
{{- $loadBalancerSourceRanges := .Values.service.fullnode.loadBalancerSourceRanges -}}

{{- if .Values.service.fullnode.enableOnchainDiscovery }}
# create internet facing network address for fullnode 
# to allow onchain discovery
{{- range $i, $e := .Values.genesis.numValidators | int | until }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-fullnode-%d" $fullName $i | quote }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- if $domain }}
    external-dns.alpha.kubernetes.io/hostname: {{ printf "fn%d.%s" $i $domain | quote }}
    {{- end }}
    alb.ingress.kubernetes.io/healthcheck-path: /-/healthy
spec:
  selector:
    app.kubernetes.io/instance: {{ printf "val%d" $i | quote }}
    app.kubernetes.io/part-of: aptos-validator
    app.kubernetes.io/name: haproxy
  ports:
  - name: aptosnet
    port: 6182
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
    {{- toYaml $loadBalancerSourceRanges | nindent 4 }}
---
{{- end }}
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "testnet.fullname" . }}-api
  labels:
    {{- include "testnet.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /-/healthy
spec:
  selector:
    app.kubernetes.io/part-of: aptos-validator
{{- if .Values.validatorLite }}
    app.kubernetes.io/name: validator
{{- else }}
    app.kubernetes.io/name: haproxy
{{- end }}
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
  externalTrafficPolicy: Local

---
{{- if .Values.service.pfn.exposeApi }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "testnet.fullname" . }}-pfn
  labels:
    {{- include "testnet.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /-/healthy
spec:
  selector:
    app.kubernetes.io/part-of: aptos-fullnode
    app.kubernetes.io/name: fullnode
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
  externalTrafficPolicy: Local
{{- end }}