apiVersion: v1
kind: Service
metadata:
  name: {{ include "testnet.fullname" . }}-waypoint
  labels:
    {{- include "testnet.labels" . | nindent 4 }}
    app: {{ include "testnet.fullname" . }}-waypoint
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  selector:
    {{- include "testnet.selectorLabels" . | nindent 4 }}
    app: {{ include "testnet.fullname" . }}-waypoint
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testnet.fullname" . }}-waypoint
  labels:
    {{- include "testnet.labels" . | nindent 4 }}
    app: {{ include "testnet.fullname" . }}-waypoint
spec:
  selector:
    matchLabels:
      {{- include "testnet.selectorLabels" . | nindent 6 }}
      app: {{ include "testnet.fullname" . }}-waypoint
  template:
    metadata:
      labels:
        {{- include "testnet.selectorLabels" . | nindent 8 }}
        app: {{ include "testnet.fullname" . }}-waypoint
    spec:
      containers:
      - name: http
        image: pierrezemb/gostatic
        imagePullPolicy: IfNotPresent
        args: ["-port", "8080", "-enable-health"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: genesis
          mountPath: /srv/http
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      volumes:
      - name: genesis
        configMap:
          name: {{ include "testnet.fullname" . }}-genesis-e{{ .Values.genesis.era }}
      serviceAccountName: {{ include "testnet.serviceAccountName" . }}
