[package]
name = "smoke-test"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos end to end tests"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bcs = "0.1.3"
diesel = { version = "1.4.8", features = ["chrono", "postgres", "r2d2", "numeric", "serde_json"] }
hex = "0.4.3"
proptest = "1.0.0"
reqwest = { version = "0.11.10", features = ["json"] }
serde_json = "1.0.81"
tokio = { version = "1.8.1", features = ["full"] }

aptos = { path = "../../crates/aptos" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-indexer = { path = "../../ecosystem/indexer" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
cached-framework-packages =  { path = "../../aptos-move/framework/cached-packages" }
forge = { path = "../forge" }
move-deps = { path = "../../aptos-move/move-deps" }

[dev-dependencies]
base64 = "0.13.0"
futures = "0.3.12"
once_cell = "1.10.0"
rand = "0.8.3"
regex = "1.5.5"
serde_yaml = "0.8.24"

aptos-genesis-tool = { path = "../../config/management/genesis", features = ["testing"] }
aptos-global-constants = { path = "../../config/global-constants" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-management = { path = "../../config/management", features = ["testing"] }
aptos-operational-tool = { path = "../../config/management/operational", features = ["testing"] }
aptos-secure-storage = { path = "../../secure/storage", features = ["testing"] }
aptos-time-service = { path = "../../crates/aptos-time-service", features = ["testing"] }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-vault-client = { path = "../../secure/storage/vault", features = ["fuzzing"] }
aptos-writeset-generator = { path = "../../aptos-move/writeset-transaction-generator" }
backup-cli = { path = "../../storage/backup/backup-cli" }
debug-interface = { path = "../../crates/debug-interface" }

[[test]]
name = "forge"
harness = false

[[test]]
name = "forge-aptos"
harness = false
