[package]
name = "forge-cli"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos end to end test framework CLI"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.53"
structopt = "0.3.21"
tokio = { version = "1.8.1", features = ["full"] }
url = "2.2.2"

aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
cached-framework-packages = { path = "../../aptos-move/framework/cached-packages" }
forge = { path = "../forge" }
testcases = { path = "../testcases" }

[[bin]]
name = "forge"
path = "src/main.rs"
