[package]
name = "transaction-builder-generator"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos transaction-builder"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
heck = "0.3.2"
regex = "1.5.5"
serde-generate = { git = "https://github.com/aptos-labs/serde-reflection" }
serde-reflection = { git = "https://github.com/aptos-labs/serde-reflection" }
serde_yaml = "0.8.24"
structopt = "0.3.21"
textwrap = "0.15.0"

aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
move-deps = { path = "../move-deps", features = ["address32"] }

[dev-dependencies]
tempfile = "3.3.0"
which = "4.2.5"

cached-framework-packages = { path = "../framework/cached-packages" }

[features]
default = []

[[bin]]
name = "generate-transaction-builders"
path = "src/generate.rs"
test = false
