[package]
name = "forge"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos end to end test framework"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
async-trait = "0.1.53"
futures = "0.3.12"
hyper = { version = "0.14.18", features = ["full"] }
hyper-proxy = "0.9.1"
hyper-tls = "0.5.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_15"] }
kube = "0.51.0"
rand = "0.8.3"
rayon = "1.5.2"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
rusoto_core = "0.46.0"
rusoto_credential = "0.46.0"
rusoto_eks = "0.46.0"
rusoto_sts = "0.46.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
structopt = "0.3.21"
tempfile = "3.3.0"
termcolor = "1.1.2"
tokio = { version = "1.8.1", features = ["full"] }
url = "2.2.2"

aptos-config = { path = "../../config" }
aptos-genesis-tool = { path = "../../config/management/genesis" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-retrier = { path = "../../crates/aptos-retrier" }
aptos-sdk = { path = "../../sdk" }
aptos-secure-storage = { path = "../../secure/storage" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
cached-framework-packages = { path = "../../aptos-move/framework/cached-packages" }
debug-interface = { path = "../../crates/debug-interface" }
transaction-emitter = { path = "../../crates/transaction-emitter" }
