[package]
name = "aptos-mempool"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos mempool for consuming incoming transactions"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bcs = "0.1.3"
fail = "0.5.0"
futures = "0.3.12"
itertools = "0.10.0"
mirai-annotations = "1.12.0"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
rand = "0.8.3"
rayon = "1.5.2"
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"
thiserror = "1.0.31"
tokio = { version = "1.8.1", features = ["full"] }
tokio-stream = "0.1.4"

aptos-config = { path = "../config" }
aptos-crypto = { path = "../crates/aptos-crypto" }
aptos-infallible = { path = "../crates/aptos-infallible" }
aptos-logger = { path = "../crates/aptos-logger" }
aptos-metrics = { path = "../crates/aptos-metrics" }
aptos-proptest-helpers = { path = "../crates/aptos-proptest-helpers", optional = true }
aptos-types = { path = "../types" }
aptos-workspace-hack = { path = "../crates/aptos-workspace-hack" }
bounded-executor = { path = "../crates/bounded-executor" }
channel = { path = "../crates/channel" }
event-notifications = { path = "../state-sync/inter-component/event-notifications" }
mempool-notifications = { path = "../state-sync/inter-component/mempool-notifications" }
netcore = { path = "../network/netcore" }
network = { path = "../network" }
short-hex-str = { path = "../crates/short-hex-str" }
storage-interface = { path = "../storage/storage-interface" }
storage-service = { path = "../storage/storage-service", optional = true }
vm-validator = { path = "../vm-validator" }

[dev-dependencies]
enum_dispatch = "0.3.8"
proptest = "1.0.0"

aptos-config = { path = "../config", features = ["fuzzing"] }
aptos-id-generator = { path = "../crates/aptos-id-generator" }
network = { path = "../network", features = ["fuzzing"] }
storage-interface = { path = "../storage/storage-interface", features = ["fuzzing"] }

[features]
default = []
failpoints = ["fail/failpoints", "vm-validator/failpoints"]
fuzzing = ["proptest", "aptos-types/fuzzing", "storage-interface/fuzzing", "aptos-config/fuzzing"]
