chain:
  name: devnet
  era: 1
  chain_id: 4

imageTag: devnet
nameOverride: aptos-validator

validator:
  name:
  image:
    repo: aptoslab/validator
    tag:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 4
      memory: 6.5Gi
    requests:
      cpu: 4
      memory: 6.5Gi
  storage:
    class:
    size: 350Gi
  rust_log: info
  rust_log_remote: debug,hyper=off
  nodeSelector: {}
  tolerations: []
  affinity: {}
  config:
    provide_genesis: true
    sync_only: false
    concurrency_level: 4
    mempool_poll_count:
    round_initial_timeout_ms:
    ledger_prune_window: 10000000
    state_store_prune_window: 1000000
    pruning_batch_size: 10000

vault:
  image:
    repo: vault
    tag: 1.8.1@sha256:d35855569d87911f396bf951104ff6603ca1858ef2283719a935f8bcf9167e64
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 0.1
      memory: 128Mi
    requests:
      cpu: 0.1
      memory: 128Mi
  server:
    address:
  serverIPRanges: []
  prometheusTarget:
  tls: {}
  auth:
    type: kubernetes
    mount_path: auth/kubernetes-aptos
    config:
      role: aptos-<role>
  namespace: aptos

service:
  external:
    type: LoadBalancer
  validator:
    loadBalancerSourceRanges:
  monitoring:
    loadBalancerSourceRanges:

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# Exposes the validator's REST API
exposeValidatorRestApi: false
# Gives certain serviceaccounts access to privileged role. Useful for profiling and performance bencharmking
enablePrivilegedMode: false
# Allow public fullnode to connect to validator directly
allowPublicFullnode: false
