[package]
name = "x-core"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Core data structures used by x"
edition = "2018"
publish = false
license = "Apache-2.0"

[dependencies]
camino = { version = "1.0.3", features = ["serde1"] }
debug-ignore = "1.0.1"
determinator = "0.8.0"
guppy = "0.13.0"
hakari = { version = "0.9.0", features = ["cli-support"] }
hex = "0.4.3"
indoc = "1.0.3"
log = "0.4.17"
once_cell = "1.10.0"
ouroboros = "0.9.2"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"
