[package]
name = "aptos-rest-client"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos REST client"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[features]
default = ["dpn"]
dpn = []

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
hex = "0.4.3"
reqwest = { version = "0.11.10", features = ["json", "cookies"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.8.1", features = ["full"] }
url = "2.2.2"

aptos-api-types = { path = "../../api/types" }
aptos-crypto = { path = "../aptos-crypto" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-workspace-hack = { path = "../aptos-workspace-hack" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }
