[package]
name = "aptos-sdk"
version = "0.0.3"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "The Official Aptos SDK"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.3"
rand_core = "0.6.2"
serde = { version = "1.0.137", features = ["derive"] }

aptos-crypto = { path = "../crates/aptos-crypto" }
aptos-transaction-builder = { path = "./transaction-builder" }
aptos-types = { path = "../types" }
aptos-workspace-hack = { path = "../crates/aptos-workspace-hack" }
move-deps = { path = "../aptos-move/move-deps", features = ["address32"] }
