[package]
name = "aptos-transaction-replay"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Replay transactions stored on chain"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
difference = "2.0.0"
hex = "0.4.3"
structopt = "0.3.21"

aptos-resource-viewer = { path = "../aptos-resource-viewer" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-validator-interface = { path = "../aptos-validator-interface" }
aptos-vm = { path = "../aptos-vm" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
aptosdb = { path = "../../storage/aptosdb" }
cached-framework-packages =  { path = "../framework/cached-packages" }
framework =  { path = "../framework" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "table-extension"] }

[dev-dependencies]
vm-genesis = { path = "../vm-genesis" }
