chain:
  name: premainnet
  era: 21
  chain_id: 21

imageTag: release-1.5_b0cbf54f

validator:
  name:
  image:
    repo: aptoslab/validator
    tag:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 4
      memory: 6.5Gi
    requests:
      cpu: 4
      memory: 6.5Gi
  storage:
    class:
    size: 350Gi
  rust_log: info
  rust_log_remote: debug,hyper=off
  nodeSelector: {}
  tolerations: []
  affinity: {}
  config:
    enable_state_sync_v2: false
    provide_genesis: true
    sync_only: false
    concurrency_level: 4
    mempool_poll_count:
    round_initial_timeout_ms:
    ledger_prune_window: 10000000
    state_store_prune_window: 1000000
    pruning_batch_size: 10000

tools:
  image:
    repo: aptoslab/tools
    tag:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 0.5
      memory: 512Mi
    requests:
      cpu: 0.5
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

backup:
  image:
    repo: aptoslab/tools
    tag:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    annotations: {}
  enable: true
  config:
    location:
    s3:
      bucket:
    gcs:
      bucket:
    azure:
      account:
      container:
      sas:
    scw_s3:
      access_key:
      secret_key:
      region:
      endpoint_url:
      bucket:
    state_snapshot_interval: 200000
    transaction_batch_size: 100000

backup_verify:
  schedule: "@daily"
  resources:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 1Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}

restore:
  image:
    repo: aptoslab/tools
    tag:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 4
      memory: 6.5Gi
    requests:
      cpu: 4
      memory: 6.5Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  config:
    location:
    s3:
      bucket:
    gcs:
      bucket:
    azure:
      account:
      container:
      sas:
    trusted_waypoints: []
    concurrent_downloads: 2
    restore_era:

fullnode:
  groups:
  - name: fullnode
    replicas: 1
    enableRestApi: true
  resources:
    limits:
      cpu: 4
      memory: 6.5Gi
    requests:
      cpu: 4
      memory: 6.5Gi
  storage:
    class:
    size: 350Gi
  rust_log: info
  rust_log_remote: debug,hyper=off
  nodeSelector: {}
  tolerations: []
  affinity: {}
  config:
    max_inbound_connections: 1000

keymanager:
  image:
    repo: aptoslab/validator_tcb
    tag:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 0.25
      memory: 256Mi
    requests:
      cpu: 0.25
      memory: 256Mi
  rust_log: debug
  rust_log_remote: debug,hyper=off
  nodeSelector: {}
  tolerations: []
  affinity: {}

vault:
  image:
    repo: vault
    tag: 1.8.1@sha256:d35855569d87911f396bf951104ff6603ca1858ef2283719a935f8bcf9167e64
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 0.1
      memory: 128Mi
    requests:
      cpu: 0.1
      memory: 128Mi
  server:
    address:
  serverIPRanges: []
  prometheusTarget:
  tls: {}
  auth:
    type: kubernetes
    mount_path: auth/kubernetes-aptos
    config:
      role: aptos-<role>
  namespace: aptos

haproxy:
  replicas: 1
  image:
    repo: haproxy
    tag: 2.2.14@sha256:36aa98fff27dcb2d12c93e68515a6686378c783ea9b1ab1d01ce993a5cbc73e1
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  limits:
    validator:
      connectionsPerIPPerMin: 2
  config:
    send_proxy_protocol: false
  tls_secret:

monitoring:
  fullKubernetesScrape: false
  useKubeStateMetrics: false
  prometheus:
    remote_write:
      enabled: false
      url:
      region:
    image:
      repo: prom/prometheus
      tag: v2.34.0@sha256:cb42332b66ac51a05c52f255e48a4496c0a172676093123bf28b37762009e78a
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1.5Gi
      requests:
        cpu: 1
        memory: 1.5Gi
    storage:
      class:
      size: 100Gi
  pushgateway:
    image:
      repo: prom/pushgateway
      tag: v1.4.1@sha256:b561435cb17ee816c5d90c2408bcc1ffe25304f1608e18db16a3969f6cc44626
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 0.1
        memory: 128Mi
      requests:
        cpu: 0.1
        memory: 128Mi
  alertmanager:
    alertRouteTrees:
      - match:
          severity: critical
        receiver: 'critical'
      - match:
          severity: error
        receiver: 'error'
    alertReceivers:
      - name: 'critical'
      - name: 'error'
      - name: 'default'
    image:
      repo: prom/alertmanager
      tag: v0.24.0@sha256:b1ba90841a82ea24d79d4e6255b96025a9e89275bec0fae87d75a5959461971e
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 0.1
        memory: 128Mi
      requests:
        cpu: 0.1
        memory: 128Mi
  grafana:
    image:
      repo: grafana/grafana
      tag: 8.4.4@sha256:b1a82a9f837ce269542cc023f0607753ca7f709195d2bdec93e2e703fd13f8c0
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 0.2
        memory: 128Mi
      requests:
        cpu: 0.2
        memory: 128Mi
  haproxy:
    clientCertVerificationDisabled: false
    resources:
      limits:
        cpu: 0.1
        memory: 256Mi
      requests:
        cpu: 0.1
        memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    annotations: {}

logging:
  vector:
    verifyServer: # default is true
    logToFile: false
    image:
      repo: timberio/vector
      tag: 0.20.0-alpine@sha256:1b6a76585ccb0a764b6374fe448825f1f46d40c3a05473337dad7c2e1f7322b5
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1.5
        memory: 2Gi
      requests:
        cpu: 1.5
        memory: 2Gi
    outputs: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  external:
    type: LoadBalancer
  validator:
    loadBalancerSourceRanges:
  fullnode:
    loadBalancerSourceRanges:
  monitoring:
    loadBalancerSourceRanges:

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# Secrets for logging and monitoring
tlsCert:
tlsKey:
clientCert:

loggingClientCert:
loggingClientKey:
loggingCA:
loggingCentralHost:

# Used for testing purposes only!
# Exposes the validator's REST API in addition to that of its VFN
exposeValidatorRestApi: false
# Used for testing purposes only!
# Gives certain serviceaccounts access to privileged role. Useful for profiling and performance bencharmking
enablePrivilegedMode: false
