[package]
name = "aptos-telemetry"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos telemetry utilities"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
once_cell = "1.10.0"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = "1.0.81"
sysinfo = "0.23.11"
tokio = { version = "1.8.1" }
uuid = { version = "1.0.0", features = ["v4", "serde"] }

aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics = { path = "../../crates/aptos-metrics" }
aptos-workspace-hack = { path = "../aptos-workspace-hack" }
