[package]
name = "x-lint"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Lint engine for x"
edition = "2018"
publish = false
license = "Apache-2.0"

[dependencies]
camino = "1.0.3"
guppy = "0.13.0"
hakari = "0.9.0"

x-core = { path = "../x-core" }
